export const seasons = [
    { id: 1, name: 'Зима', startDate: '2023-12-01', endDate: '2024-02-28' },
    { id: 2, name: 'Весна', startDate: '2024-03-01', endDate: '2024-05-31' },
    { id: 3, name: 'Лето', startDate: '2024-06-01', endDate: '2024-08-31' },
    { id: 4, name: 'Осень', startDate: '2024-09-01', endDate: '2024-11-30' },
];

export const touristsCategories = [
    { id: 1, name: 'Новичок', description: '' },
    { id: 2, name: 'Любитель', description: '' },
    { id: 3, name: 'Продвинутый', description: '' },
    { id: 4, name: 'Эксперт', description: '' },
];

export const guidesCategories = [
    { id: 1, name: 'Начальный', description: '' },
    { id: 2, name: 'Продвинутый', description: '' },
    { id: 3, name: 'Эксперт', description: '' },
];

export const equipmentTypes = [
    { id: 1, name: 'Теплая одежда', season_id: 1, parent_id: null },
    { id: 2, name: 'Зимняя обувь', season_id: 1, parent_id: null },
    { id: 3, name: 'Лыжи / сноуборд', season_id: 1, parent_id: null },
    { id: 4, name: 'Снегоступы', season_id: 1, parent_id: null },
    { id: 5, name: 'Термос для горячих напитков', season_id: 1, parent_id: null },

    { id: 6, name: 'Дождевик или водонепроницаемая куртка', season_id: 2, parent_id: null },
    { id: 7, name: 'Обувь на сухую и влажную погоду', season_id: 2, parent_id: null },
    { id: 8, name: 'Палатка с защитой от дождя', season_id: 2, parent_id: null },
    { id: 9, name: 'Спальник средней температуры', season_id: 2, parent_id: null },

    { id: 10, name: 'Легкая одежда', season_id: 3, parent_id: null },
    { id: 11, name: 'Кепка или шляпа от солнца', season_id: 3, parent_id: null },
    { id: 12, name: 'Солнцезащитный крем', season_id: 3, parent_id: null },
    { id: 13, name: 'Палатка с москитной сеткой', season_id: 3, parent_id: null },
    { id: 14, name: 'Гамак', season_id: 3, parent_id: null },

    { id: 15, name: 'Теплая одежда', season_id: 4, parent_id: null },
    { id: 16, name: 'Водонепроницаемая обувь', season_id: 4, parent_id: null },
    { id: 17, name: 'Палатка с защитой от дождя', season_id: 4, parent_id: null },
    { id: 18, name: 'Термос для горячих напитков', season_id: 4, parent_id: null },
];

export const equipment = [
    {
        id: 1,
        name: 'Теплая одежда M',
        weight: 1.5,
        value: 100,
        rentPrice: 10,
        count: 10,
        equipment_type_id: 1,
    },
    {
        id: 2,
        name: 'Теплая одежда L',
        weight: 1.7,
        value: 120,
        rentPrice: 12,
        count: 10,
        equipment_type_id: 1,
    },
    {
        id: 3,
        name: 'Зимняя обувь 42 размер',
        weight: 1.0,
        value: 80,
        rentPrice: 8,
        count: 10,
        equipment_type_id: 2,
    },
    {
        id: 4,
        name: 'Зимняя обувь 44 размер',
        weight: 1.1,
        value: 90,
        rentPrice: 9,
        count: 10,
        equipment_type_id: 2,
    },
    { id: 5, name: 'Лыжи 160 см', weight: 3.0, value: 200, rentPrice: 20, count: 10, equipment_type_id: 3 },
    { id: 6, name: 'Лыжи 170 см', weight: 3.2, value: 220, rentPrice: 22, count: 10, equipment_type_id: 3 },
    {
        id: 7,
        name: 'Снегоступы 25"',
        weight: 2.0,
        value: 150,
        rentPrice: 15,
        count: 10,
        equipment_type_id: 4,
    },
    {
        id: 8,
        name: 'Снегоступы 30"',
        weight: 2.2,
        value: 160,
        rentPrice: 16,
        count: 10,
        equipment_type_id: 4,
    },
    { id: 9, name: 'Термос 0.5 л', weight: 0.5, value: 50, rentPrice: 5, count: 10, equipment_type_id: 5 },
    { id: 10, name: 'Термос 1.0 л', weight: 0.7, value: 70, rentPrice: 7, count: 10, equipment_type_id: 5 },
    { id: 11, name: 'Дождевик M', weight: 0.5, value: 70, rentPrice: 7, count: 10, equipment_type_id: 6 },
    { id: 12, name: 'Дождевик L', weight: 0.6, value: 80, rentPrice: 8, count: 10, equipment_type_id: 6 },
    {
        id: 13,
        name: 'Обувь на сухую погоду 42 размер',
        weight: 0.8,
        value: 60,
        rentPrice: 6,
        count: 10,
        equipment_type_id: 7,
    },
    {
        id: 14,
        name: 'Обувь на сухую погоду 44 размер',
        weight: 0.9,
        value: 70,
        rentPrice: 7,
        count: 10,
        equipment_type_id: 7,
    },
    {
        id: 15,
        name: 'Палатка с защитой от дождя 2 места',
        weight: 2.5,
        value: 200,
        rentPrice: 20,
        count: 10,
        equipment_type_id: 8,
    },
    {
        id: 16,
        name: 'Палатка с защитой от дождя 4 места',
        weight: 4.5,
        value: 350,
        rentPrice: 35,
        count: 10,
        equipment_type_id: 8,
    },
    {
        id: 17,
        name: 'Спальник средней температуры M',
        weight: 1.0,
        value: 100,
        rentPrice: 10,
        count: 10,
        equipment_type_id: 9,
    },
    {
        id: 18,
        name: 'Спальник средней температуры L',
        weight: 1.2,
        value: 120,
        rentPrice: 12,
        count: 10,
        equipment_type_id: 9,
    },
    {
        id: 19,
        name: 'Легкая одежда M',
        weight: 0.5,
        value: 50,
        rentPrice: 5,
        count: 10,
        equipment_type_id: 10,
    },
    {
        id: 20,
        name: 'Легкая одежда L',
        weight: 0.6,
        value: 60,
        rentPrice: 6,
        count: 10,
        equipment_type_id: 10,
    },
    { id: 21, name: 'Кепка', weight: 0.1, value: 20, rentPrice: 2, count: 10, equipment_type_id: 11 },
    {
        id: 22,
        name: 'Шляпа от солнца',
        weight: 0.2,
        value: 30,
        rentPrice: 3,
        count: 10,
        equipment_type_id: 11,
    },
    {
        id: 23,
        name: 'Солнцезащитный крем 50 мл',
        weight: 0.05,
        value: 10,
        rentPrice: 1,
        count: 10,
        equipment_type_id: 12,
    },
    {
        id: 24,
        name: 'Солнцезащитный крем 100 мл',
        weight: 0.1,
        value: 18,
        rentPrice: 2,
        count: 10,
        equipment_type_id: 12,
    },
    {
        id: 25,
        name: 'Палатка с москитной сеткой 2 места',
        weight: 2.5,
        value: 200,
        rentPrice: 20,
        count: 10,
        equipment_type_id: 13,
    },
    {
        id: 26,
        name: 'Палатка с москитной сеткой 4 места',
        weight: 4.5,
        value: 350,
        rentPrice: 35,
        count: 10,
        equipment_type_id: 13,
    },
    {
        id: 27,
        name: 'Гамак одноместный',
        weight: 1.0,
        value: 50,
        rentPrice: 5,
        count: 10,
        equipment_type_id: 14,
    },
    {
        id: 28,
        name: 'Гамак двухместный',
        weight: 1.5,
        value: 75,
        rentPrice: 8,
        count: 10,
        equipment_type_id: 14,
    },
    {
        id: 29,
        name: 'Теплая одежда M',
        weight: 1.5,
        value: 100,
        rentPrice: 10,
        count: 10,
        equipment_type_id: 15,
    },
    {
        id: 30,
        name: 'Теплая одежда L',
        weight: 1.7,
        value: 120,
        rentPrice: 12,
        count: 10,
        equipment_type_id: 15,
    },
    {
        id: 31,
        name: 'Водонепроницаемая обувь 42 размер',
        weight: 1.0,
        value: 80,
        rentPrice: 8,
        count: 10,
        equipment_type_id: 16,
    },
    {
        id: 32,
        name: 'Водонепроницаемая обувь 44 размер',
        weight: 1.1,
        value: 90,
        rentPrice: 9,
        count: 10,
        equipment_type_id: 16,
    },
    {
        id: 33,
        name: 'Палатка с защитой от дождя 2 места',
        weight: 2.5,
        value: 200,
        rentPrice: 20,
        count: 10,
        equipment_type_id: 17,
    },
    {
        id: 34,
        name: 'Палатка с защитой от дождя 4 места',
        weight: 4.5,
        value: 350,
        rentPrice: 35,
        count: 10,
        equipment_type_id: 17,
    },
    { id: 35, name: 'Термос 0.5 л', weight: 0.5, value: 50, rentPrice: 5, count: 10, equipment_type_id: 18 },
    { id: 36, name: 'Термос 1.0 л', weight: 0.7, value: 70, rentPrice: 7, count: 10, equipment_type_id: 18 },
];
